data:
  raw_path: "data/raw/"
  train_cutoff: "2022-12-31"
  test_start: "2024-01-01"
  target_col: "label"

  # 1. INPUT FEATURES (Used by Random Forest)
  # These are the pre-calculated Rolling Stats and Static Context.
  features: [
    "ace_roll_diff", "df_roll_diff", "1stIn_pct_roll_diff",
    "win_pct_roll_diff", "h2h_win_rate", "days_since",
    "rank", "opponent_rank",
    # We include raw rolling averages too, as trees can find non-linear interactions
    "ace_roll", "opponent_ace_roll",
    "df_roll", "opponent_df_roll",
    "win_pct_roll", "opponent_win_pct_roll"
  ]

  # 2. SEQUENCE FEATURES (Ignored by RF, but required for Schema)
  # The Preprocessor will scale these, but the Dataset won't yield them to the RF model.
  sequence_features: [
    "ace", "df", "svpt", "1stIn", "1stWon", "2ndWon",
    "rank", "winner_rank", "loser_rank"
  ]

  drop_cols: [
    "match_id", "match_uid", "player", "opponent",
    "match_num", "tourney_date", "label", "winner_name", "loser_name", "id"
  ]

  cat_cols: ["surface"]

model:
  name: "rf"  # Switch to 'logreg' for Logistic Regression
  n_estimators: 100
  max_depth: 8

train:
  batch_size: 64
  epochs: 1
  learning_rate: 0.001
  seed: 42
  tuning: False
